<div class="modal fade" id="edit-post" role="dialog">
	<div class="modal-dialog modal-md wow_mat_mdl">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['edit_post']; ?></h4>
			</div>
			<div class="modal-body edit-textarea-<?php echo $wo['story']['id'];?>" style="padding:0;">
				<textarea class="form-control" style="padding: 10px; border-radius: 0" placeholder="<?php echo $wo['lang']['edit_post']?>" dir="auto" rows="5" onkeyup="Wo_Get_Mention(this)"><?php echo $wo['story']['Orginaltext']?></textarea>
			</div>
			<div class="modal-footer" style="border: none">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button type="button" class="btn main btn-mat" id="edit-post-button" onclick="Wo_EditPost(<?php echo $wo['story']['id'];?>)" ><?php echo $wo['lang']['update']; ?></button>
			</div>
		</div>
	</div>
</div>