<tr id="UserID_<?php echo $wo['userlist']['id']?>" data-user-id="<?php echo $wo['userlist']['user']['user_id']?>">
   <td><?php echo $wo['userlist']['user']['user_id']?></td>
   <td>
      <a href="<?php echo $wo['userlist']['user']['url']; ?>">
      <img src="<?php echo $wo['userlist']['user']['avatar']; ?>" class="setting-avatar" alt="<?php echo $wo['userlist']['user']['avatar']?> Profile Picture">
      <?php echo $wo['userlist']['user']['name']; ?>
      </a>
      <span class="pointer toggle-verification-request" onclick="Wo_ToggleVerfRequest(<?php echo $wo['userlist']['id']; ?>,this)">
         <i class="fa fa-caret-down" aria-hidden="true"></i>
      </span>
   </td>
   <td><?php echo $wo['userlist']['user']['paypal_email'];?></td>
   <td>$<?php echo $wo['userlist']['amount'];?></td>
   <td><a href="<?php echo Wo_LoadAdminLinkSettings('referrals-list?id=' . $wo['userlist']['user_id']); ?>">Show</a></td>
   <td>
   <?php 
   if ($wo['userlist']['status'] == 0) {
      echo '<span class="label label-warning">Pending</span>';
   } else 
   if ($wo['userlist']['status'] == 1) {
      echo '<span class="label label-success">Approved</span>';
   } else
   if ($wo['userlist']['status'] == 2) {
      echo '<span class="label label-danger">Declined</span>';
   }
   ?></td>
   <td>
      <button onclick="Wo_MarkPaid(<?php echo $wo['userlist']['id']?>);" type="button" class="btn btn-success waves-effect waves-light">PAID</button>
      <button onclick="Wo_DeclinePayment(<?php echo $wo['userlist']['id']?>);" type="button" class="btn btn-danger waves-effect waves-light">DECLINE</button>
   </td>
</tr>
<tr id="review-verif-request-info-<?php echo $wo['userlist']['id']; ?>" style="display: none;">
   <td colspan="4">
      <div class="review-verif-request-cont">
         <h4>IBAN :  <small><?php echo $wo['userlist']['iban']; ?></small></h4>
         <h4>Country :  <small><?php echo $wo['userlist']['country']; ?></small></h4>
         <h4>Full Name :  <small><?php echo $wo['userlist']['full_name']; ?></small></h4>
         <h4>Swift Code :  <small><?php echo $wo['userlist']['swift_code']; ?></small></h4>
         <h4>Address :  <small><?php echo $wo['userlist']['address']; ?></small></h4>
      </div>
   </td>
</tr>
