<div class="container-fluid">
    <div class="block-header">
        <h2>Pro System > Manage Pro Refund</h2>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Pro Refund Reqeusts</h2>
                </div>
                <div class="body">
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                      <th>ID</th>
					                  <th>User</th>
					                  <th>Status</th>
					                  <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                $requests = $db->get(T_REFUND);
                                if (!empty($requests)) {
          				                foreach ($requests as $wo['verification']) {
                                    $wo['verification'] = (Array)$wo['verification'];
                                    $wo['verification']['user_data'] = Wo_UserData($wo['verification']['user_id']);
                                    $user_pro_type = Wo_GetUserProType($wo['verification']['user_data']['pro_type']);
                                    $wo['verification']['type_name'] = $user_pro_type['type_name'];
          				                    echo Wo_LoadAdminPage('pro-refund/list');
          				                }
                                }
				                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

function Wo_DeleteRefund(id) {
  var delete_icon = $('.setting-verification-container').find('#VerificationID_' + id).find('.delete-verification');
  $('#review-verif-request-info-'+id).slideUp(function(){
        $(this).remove();
        $('#VerificationID_' + id).fadeOut(300, function() {
          $(this).remove();
        });
      })
  $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s:'delete_refund', id:id});
}

function Wo_ApproveRefund(id) {
  $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s:'approve_refund', id:id}, function(data) {
    if (data.status == 200) {
      var delete_icon = $('.setting-verification-container').find('#VerificationID_' + id).find('.delete-verification');
  $('#review-verif-request-info-'+id).slideUp(function(){
        $(this).remove();
        $('#VerificationID_' + id).fadeOut(300, function() {
          $(this).remove();
        });
      })

    }
  });
}
function Wo_ToggleVerfRequest(id,self){
  if (!id || !self) {
    return false;
  }
  $(self).find('i').toggleClass('rotate-90d');
  $("#review-verif-request-info-"+id).slideToggle();

}

</script>

<style>
  .review-verif-request-cont{
    width: 100%;
    overflow: hidden;
    margin: 5px 0;
  }
  .review-verif-request-cont div{
    width: 200px;
    height: 150px;
    float: left;
    cursor: pointer;
    margin: 0 5px 5px 0;
  }

  .review-verif-request-cont h4{
    width: 100%;
    color: #666;
    font-size: 14px;
    font-weight: 600;
  }

  .toggle-verification-request{
    padding: 3px 5px;
  }
</style>